// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {display} from '../models';

export function AddProfile(arg1:string,arg2:string):Promise<main.Profile>;

export function ApplyProfile(arg1:main.Profile,arg2:number):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DuplicateProfile(arg1:string):Promise<main.Profile>;

export function GetDisplays():Promise<Array<display.DisplayInfo>>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function IsVibranceAvailable():Promise<boolean>;

export function ResetDisplay(arg1:number):Promise<void>;

export function SaveProfile(arg1:main.Profile):Promise<void>;
