// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1, arg2) {
  return window['go']['main']['App']['AddProfile'](arg1, arg2);
}

export function ApplyProfile(arg1, arg2) {
  return window['go']['main']['App']['ApplyProfile'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DuplicateProfile(arg1) {
  return window['go']['main']['App']['DuplicateProfile'](arg1);
}

export function GetDisplays() {
  return window['go']['main']['App']['GetDisplays']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function IsVibranceAvailable() {
  return window['go']['main']['App']['IsVibranceAvailable']();
}

export function ResetDisplay(arg1) {
  return window['go']['main']['App']['ResetDisplay'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}
